### PR TITLE
Merge Alt-Data-Frame-ButMore back to Data-Frame

### PR DESCRIPTION
**Pull request by stphnlyd**
This is mostly same as my last release to https://metacpan.org/dist/Alt-Data-Frame-ButMore, except the package name. 

Not sure why the CI does not run. I have travis/appveyor in my PR, maybe that's not enough here? But if no one raise any concerns I will merge this first and then look at the CI.

### CODE REVIEW

**Comment by mohawk2** [comment]
I reckon the version-bumps need dropping, and Changes entries need making accurate, since this is a different distro from the Alt one?

Also, it would probably be a good idea to get the CI config onto master first, which would then make it runnable on this?

**Comment by stphnlyd** [comment]
@mohawk2 Sure I will add the CI first. And I will rework the changelog. As for the version I would not like to have it lower than the version of Alt::Data::Frame::ButMore, as that has no harms but the other way could cause confusion.

**Comment by stphnlyd** [comment]
The new changelog https://github.com/EntropyOrg/p5-Data-Frame/pull/29/files#diff-bbd4b6a86bc65b6ac8e79e97afc61499158edb40f7bb404c70637b46d80a7ad2

**Comment by mohawk2** [comment]
Thanks for the CI. It seems Travis is truly kaput, which is a pity, and this distro should probably use the amazing PDL GHA CI. The version bump makes sense to me, and I have no opinion on the rest but I assume it makes sense. @zmughal ?

**Comment by stphnlyd** [comment]
@mohawk2 as no on else commented, I will merge this first. I think yes we can use PDL's CI, IMO we can do it in a separate work later.

**Pull request merged**
