### PR TITLE
fix PDL::Factor's ngood, nbad

### PR DESCRIPTION
**Pull request by stphnlyd**
they were good on PDL 2.035 but broken on PDL 2.063

### CODE REVIEW

**Comment by mohawk2** [comment]
Could you help me fix PDL by showing what worked one way before, and doesn't now? Breaking other people's code is not something we take lightly :-)

**Comment by stphnlyd** [comment]
@mohawk2 
I will try to find out more details, but basically: For a custom class that subclasses PDL, say $p is instance of the custom class and `$p->{PDL}` points to the internal piddle, in the old days (at least PDL 2.035's good) I could just do `$p->some_method` and expect it actually work on `$p->{PDL}`. But today with newer versions of PDL like 2.063, I find I have to explicitly call `$p->{PDL}->some_method`. 


Another separate compatibility issue is about the change of PDL's sum() method: Earlier it returns a plain scalar int, now it returns a int-typed piddle, this has some difference like when you do a `$int_value / $p->sum()`, earlier it was double division as Perl does not do C-like int division, but now it becomes int division.. See also my fix to my package at https://github.com/stphnlyd/perl5-Chart-GGPlot/pull/24/commits/91a14f40ca5537c5e9a8e954e42f07b4973341e7

**Comment by mohawk2** [comment]
For `sum` returning an ndarray, that will unfortunately have to stay, and you need to call `->sclr` to get a Perl scalar if you're sure you want that, or for the case you describe, convert the `$int_value` to `double` if you need non-int arithmetic.

For the method call, as far as I know that should still operate as you say it used to. If you can show some simple code either here or in an issue on PDL, we can look into it. Also, reporting these things on PDL is a good idea.

**Comment by zmughal** [comment]
Looks good. Let's merge this for now and later we can fix this for PDL then add a minimum version on that.

**Comment by mohawk2** [comment]
If this fixes a problem for existing users, maybe push out a new release?

By the way, @stphnlyd it looks like only you have permissions on various of the new modules such as Data::Frame::PDL - could you at the very least give @zmughal co-maint?

**Comment by stphnlyd** [comment]
@zmughal @mohawk2 now I've added both of you permission to Alt-Data-Frame-ButMore. I will update that distribution to point it to Data-Frame.

**Comment by zmughal** [comment]
Great! I've re-indexed the `ZMUGHAL/Data-Frame-0.006002.tar.gz` dist earlier today.

**Pull request merged**
